site_name: yacore
site_description: Yet Another CORE library
site_url: https://pohmelie.github.io/yacore/

theme:
  name: "material"
  favicon: "img/yacore.png"
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
  features:
    - navigation.sections

repo_name: pohmelie/yacore
repo_url: https://github.com/pohmelie/yacore
edit_uri: ""

nav:
  - Introduction: "index.md"
  - Usage:
      - New proejct: "new-project.md"
      - Service structure:
          - Entry point and configuration: "service-structure/entry-point-and-configuration.md"
          - Service: "service-structure/service.md"
          - Dependency injection: "service-structure/dependency-injection.md"
      - Backends: "backends.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

extra_css:
  - css/custom.css
